name: build mlr image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: timestamp
        id: timestamp
        run: |
          echo "::set-output name=value::$(/bin/date -u '+%Y%m%dT%T')"
        shell: bash
      - uses: actions/cache@v2
        with:
          path: podman
          key: ${{ runner.os }}-podman-${{ steps.timestamp.outputs.value }}

      - name: install
        run: |
          bin/install-on-ubuntu
          mkdir -p podman
          sudo podman export mlr > podman/mlr.tar
